YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "parserlib.css.Combinator",
        "parserlib.css.MediaFeature",
        "parserlib.css.MediaQuery",
        "parserlib.css.Parser",
        "parserlib.css.PropertyName",
        "parserlib.css.PropertyValue",
        "parserlib.css.PropertyValueIterator",
        "parserlib.css.PropertyValuePart",
        "parserlib.css.Selector",
        "parserlib.css.SelectorPart",
        "parserlib.css.SelectorSubPart",
        "parserlib.css.Specificity",
        "parserlib.css.TokenStream",
        "parserlib.css.TokenStreamBase",
        "parserlib.util.Anchor",
        "parserlib.util.BackgroundTokenizer",
        "parserlib.util.CSSLint",
        "parserlib.util.EditSession",
        "parserlib.util.Editor",
        "parserlib.util.EditorDocument",
        "parserlib.util.EventTarget",
        "parserlib.util.Fold",
        "parserlib.util.FoldLine",
        "parserlib.util.GutterTooltip",
        "parserlib.util.HScrollBar",
        "parserlib.util.HtmlMode",
        "parserlib.util.Mode",
        "parserlib.util.Position",
        "parserlib.util.Range",
        "parserlib.util.Reporter",
        "parserlib.util.ScrollBar",
        "parserlib.util.Search",
        "parserlib.util.Selection",
        "parserlib.util.StringReader",
        "parserlib.util.SyntaxError",
        "parserlib.util.SyntaxUnit",
        "parserlib.util.TokenIterator",
        "parserlib.util.Tokenizer",
        "parserlib.util.Tooltip",
        "parserlib.util.TypeScriptWorker",
        "parserlib.util.UndoManager",
        "parserlib.util.VScrollBar",
        "parserlib.util.ValidationError",
        "parserlib.util.VirtualRenderer",
        null
    ],
    "modules": [],
    "allModules": [],
    "elements": []
} };
});